travis:
  secure:
    BINSTAR_TOKEN: N1H1mrfI6oiTaKgykLALwurJJb0A61fZmd+HQE5Hlxo8CsbQRG5dplxsprm0gLDEmu4ydgpmXmOT4Tt9wq867wRupUAI0yqawhiYljla1dGe/zhoxOvQWzi8UsDrj9/qx42Ug9dKOucMRRRfCXGIYaVKH3mzZlMUQoZeX4+XFdhlaAbaih6PG8SX3mps1K6VB4ndSoR6+sVilei3HJrPo6Fmh7UnpDftyGfJSaGf5TRPt1AEp5nNzw3BCS/jv36cvHM26Uk63yDHqNT4JDL6LOm0EpjYwNTgap1NhKLmhrzuuASKilexsqA5dWlrhIo7tprorxhgkSU828GmJNcWpPE1vw5P/bDxMzE8whpBrWaRKmV82mw/kUFs9VEscF6NaIJ1QNjQ4st+TPSF9htIgRK0tqVEx1be08NkMVaVTfR5UFTWUfh+JOIWqQE/eZxhZA38wxlDj89jjaszBnDfX9jHScE5/axbnb3qq0S1iX3/ZYtQMEBbZzJsd3IjHX0fr1R13vILUK8ejcQo/g66VtGpE1J1RTNjpFKgzb8tBHY5QTZ/RtX6gEoBPFrxNJi08lpxwT5lv2awpGWK53ImT9HSTOrf2CKh8LlLXVl0MTJGPFGtL2ggQ2tciY2rnY2OaBBmT51CzyJK02CIHXWuUAMlq1v9qiQOKJx2sWnIrSY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
